server {
    server_name browser-agent.project-kk.com www.browser-agent.project-kk.com;

    # アップロード上限
    client_max_body_size 10M;

    location / {

        proxy_pass         http://127.0.0.1:5007;
        proxy_http_version 1.1;

        # WebSocket サポート
        proxy_set_header Upgrade    $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_read_timeout  300s;
        proxy_send_timeout  300s;
        proxy_connect_timeout 10s;
    }

    location /vnc/ {
        proxy_pass http://127.0.0.1:7900/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/browser-agent.project-kk.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/browser-agent.project-kk.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot


}
server {
    if ($host = www.browser-agent.project-kk.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    if ($host = browser-agent.project-kk.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    server_name browser-agent.project-kk.com www.browser-agent.project-kk.com;
    return 404; # managed by Certbot




}